# Generated by Django 5.1.6 on 2025-03-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("table_number", models.IntegerField()),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("is_pending", "в ожидании"),
                            ("is_ready", "готово"),
                            ("is_paid", "оплачено"),
                        ],
                        default="is_pending",
                    ),
                ),
                (
                    "items",
                    models.ManyToManyField(
                        related_name="items", to="cafe_control.item"
                    ),
                ),
            ],
        ),
    ]
