# Generated by Django 5.1.6 on 2025-03-06 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cafe_control", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="orderitem",
            unique_together={("order", "item")},
        ),
    ]
